qualquer=input('Digite qualquer Coise: ')
print('O tipo que de dados que você digitou é um valor ', type(qualquer))
print('Só tem espaços? ', qualquer.isspace())
print('É um número? ', qualquer.isnumeric())
print('É alfabético ? ', qualquer.isalpha())
print('É alfanumérico? ', qualquer.isalnum())
print('Está em maiúcula? ', qualquer.isupper())
print('Está em minúscula ? ', qualquer.islower())
print('Está capitalizado? ', qualquer.istitle())
